name: 'ALOG to Image'
description: 'Render Artisan roaster .alog files to PNG images and maintain a roast log'
author: 'jmillsy'

branding:
  icon: 'coffee'
  color: 'orange'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install matplotlib>=3.5.0
    
    - name: Process alog files
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        mkdir -p renders
        
        # Get list of changed .alog files
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          changed_alogs=$(find . -name "*.alog" -type f -not -path "./.git/*")
        else
          changed_alogs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.alog$' || true)
        fi
        
        if [ -z "$changed_alogs" ]; then
          echo "No alog files to process"
          exit 0
        fi
        
        # Process each alog file
        echo "$changed_alogs" | while read alog; do
          if [ -f "$alog" ]; then
            echo "Processing $alog..."
            
            # Extract batch number
            batch_name=$(python3 -c "import ast; data = ast.literal_eval(open('$alog').read()); print(f\"{data.get('roastbatchprefix', '#')}{data.get('roastbatchnr', 0)}\")" 2>/dev/null || echo "unknown")
            
            # Render profile
            python3 "${ACTION_PATH}/alog_renderer.py" "$alog" -o "renders/${batch_name}.png"
            
            # Update roast log if it exists
            if [ -f "roasts.md" ]; then
              python3 "${ACTION_PATH}/update_roast_log.py" "$alog" "renders/${batch_name}.png"
            fi
            
            echo "✓ Processed: $batch_name"
          fi
        done
    
    - name: Commit changes
      shell: bash
      run: |
        echo "Configuring git..."
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        echo "Checking for files to commit..."
        ls -la renders/ 2>/dev/null || echo "No renders directory"
        ls -la roasts.md 2>/dev/null || echo "No roasts.md file"
        
        echo "Adding files to git..."
        git add renders/ roasts.md 2>&1 || echo "Note: Some files may not exist yet"
        
        echo "Checking git status..."
        git status
        
        if ! git diff --staged --quiet; then
          echo "Committing changes..."
          git commit -m "Add roast profile renders and update roast log [skip ci]"
          echo "Pushing to repository..."
          git push
          echo "✓ Successfully committed and pushed changes"
        else
          echo "⚠ No changes to commit - this might indicate an issue"
        fi
