name: 'ALOG to Image'
description: 'Render Artisan roaster .alog files to PNG images and maintain a roast log'
author: 'jmillsy'

branding:
  icon: 'coffee'
  color: 'orange'

inputs:
  github-token:
    description: 'GitHub token for committing changes'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install matplotlib>=3.5.0
    
    - name: Process alog files
      shell: bash
      run: |
        mkdir -p renders
        
        # Get list of changed .alog files
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          changed_alogs=$(find . -name "*.alog" -type f -not -path "./.git/*")
        else
          changed_alogs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.alog$' || true)
        fi
        
        if [ -z "$changed_alogs" ]; then
          echo "No alog files to process"
          exit 0
        fi
        
        # Process each alog file
        echo "$changed_alogs" | while read alog; do
          if [ -f "$alog" ]; then
            echo "Processing $alog..."
            
            # Extract batch number
            batch_name=$(python -c "
import ast
try:
    data = ast.literal_eval(open('$alog').read())
    prefix = data.get('roastbatchprefix', '#')
    number = data.get('roastbatchnr', 0)
    print(f'{prefix}{number}')
except:
    print('unknown')
")
            
            # Render profile
            python ${{ github.action_path }}/alog_renderer.py "$alog" -o "renders/${batch_name}.png"
            
            # Update roast log if it exists
            if [ -f "ROASTS.md" ]; then
              python ${{ github.action_path }}/update_roast_log.py "$alog" "renders/${batch_name}.png"
            fi
            
            echo "✓ Processed: $batch_name"
          fi
        done
    
    - name: Commit changes
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        git add renders/*.png ROASTS.md 2>/dev/null || true
        
        if ! git diff --staged --quiet; then
          git commit -m "Add roast profile renders and update roast log [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
